#!/bin/bash

if [ $# -lt 1 ]; then
  echo ""
  echo "        Usage: $0 [APP] [other args]"
  echo ""
  exit 1
fi

APP=$1
shift 1

CONF=tmp/$APP.cfg
#Note: can't follow non-constant source from dynamic input entry APP, as APP=$1
#shellcheck disable=SC1090
. "$CONF" || exit $?

"$BUILD"/bin/fd_frank_mon.bin "$MON_ARGS" "$@"

